### PR TITLE
Fixed failed `gom install`

### PR DESCRIPTION
**Pull request by yudppp**
https://github.com/mattn/gom/issues/66

Add ignore package

```
ignore ex)
github.com/hoge/fuga/examples
github.com/hoge/fuga/examples/hoga
github.com/foo/bar/_test
github.com/foo/bar/_test/baz
```

### CODE REVIEW

**Comment by yudppp** [comment]
> please look directory name that has prefix _ too. ex: /_xxx .

d3e3ad458de8c7d8c364f7611fce127264cc782f

Add ignore package.

**Comment by mattn** [comment]
LGTM

**Comment by mattn** [comment]
Thank you.

**Comment by miry** [comment]
After this commit I could not install `gom 'github.com/pquerna/ffjson'`

```
github.com/pquerna/ffjson/tests/go.stripe
go build github.com/pquerna/ffjson/tests/go.stripe: no buildable Go source files in /gopath/src/github.com/pubnative/ad_server/_vendor/src/github.com/pquerna/ffjson/tests/go.stripe
gom:  exit status 1
```

**Comment by miry** [comment]
sorry wrong PR it is in commit f4cb457f0d620b7c062d0b48fc08ca901f274560

**Comment by mattn** [comment]
https://github.com/mattn/gom/commit/f4cb457f0d620b7c062d0b48fc08ca901f274560 is fixed by this PR. do you have still issue?

**Comment by miry** [comment]
@mattn yes.

**Comment by mattn** [comment]
@miry fixed. could you please try last commit?

**Comment by miry** [comment]
thanks

**Pull request merged**
